### ISSUE TITLE
Switch nixpkgs to nixos-unstable

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/infra#28]
Accidentally left it at nixpkgs-stable when initializing

**Comment by TheKodeToad** [comment]
I know nothing about nix, but stable sounds a bit more appealing for a server

**Comment by TayouVR** [comment]
I find this incredibly funny for some reason

**Comment by Scrumplex** [comment]
> I know nothing about nix, but stable sounds a bit more appealing for a server

Stable is a myth invented by the LTS lobby!!!!
